DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS job;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE job (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    valid INTEGER NOT NULL,
    user TEXT NOT NULL
);